name: ci

on:
  push:
  pull_request:

env:
  CONTINUOUS_INTEGRATION: true

jobs:
  build-success:
    if: ${{ !success() }} # if `failure()` would not work for cancellations
    runs-on: ubuntu-latest
    needs:
      [
        amt,
        b,
        cs,
      ]
    steps:
      - run: false

  amt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        p: [1, 2]
    steps:
      - uses: actions/checkout@v4
      - name: "test"
        run: "true"

  b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "test"
        run: "true"

  cs:
    runs-on: ubuntu-latest
    if: "github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'duplicate')"
    steps:
      - uses: actions/checkout@v4
      - name: "test"
        run: "true"
